
# Monitors
monitor=eDP-1,1920x1080@60,0x0,1

# My Programs
$terminal = kitty
$fileManager = thunar
$menu = rofi -show-icons -show drun
$browser = brave-origin

# Autostart Applictaions
exec-once = waybar
exec-once = nm-applet
exec-once = blueman-applet
exec-once = awww-daemon
exec-once = swaync
exec-once = hypridle
exec-once = /usr/libexec/polkit-mate-authentication-agent-1

# Environment Variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Look And Feel 
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/decoration.conf
source = ~/.config/hypr/hyprland/layout.conf
source = ~/.config/hypr/hyprland/animations.conf

# Input
source = ~/.config/hypr/hyprland/input.conf

# Keybindings
source = ~/.config/hypr/hyprland/keybindings.conf

# Windows And Workspaces 

source = ~/.config/hypr/hyprland/windows_rules.conf
